const editorLanguageMap = {
    'bash': 'bash',
    'c': 'c',
    'csharp': 'c#',
    'cpp': 'c++',
    'css': 'css',
    'dart': 'dart',
    'elixir': 'elixir',
    'elm': 'elm',
    'gml': 'gml',
    'gdscript': 'gdscript',
    'git': 'git',
    'go': 'go',
    'graphql': 'graphql',
    'haskell': 'haskell',
    'html': 'html',
    'java': 'java',
    'javascript': 'javascript',
    'json': 'json',
    'jsx': 'jsx',
    'kotlin': 'kotlin',
    'latex': 'latex',
    'less': 'less',
    'lisp': 'lisp',
    'lua': 'lua',
    'markdown': 'markdown',
    'objectivec': 'objective c',
    'perl': 'perl',
    'php': 'php',
    'python': 'python',
    'regex': 'regex',
    'ruby': 'ruby',
    'rust': 'rust',
    'sass': 'sass',
    'sql': 'sql',
    'stylus': 'stylus',
    'swift': 'swift',
    'typescript': 'typescript',
    'visual-basic': 'visual basic',
    'wasm': 'web assembly',
    'yaml': 'yaml',
};

export default editorLanguageMap;
